spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hsiaotien/springcloudinaction/
          search-paths: config-repo
          username: hsiaotien@163.com
          password: Hh12345@
server:
  port: 7001
